name: Dagger

on:
  push:
    branches:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dagger
        uses: dagger/dagger-action@v1
        with:
          age-key: ${{ secrets.DAGGER_AGE_KEY }}
          args: version

      - name: Up
        run: |
          echo "Use local dev dagger until > 0.1.0-alpha.30 ships..."
          echo "# /opt/hostedtoolcache/dagger/*/x64/dagger up --environment ci"
          ./dagger up --environment ci
